function entry = help_content(key)
%UI_HELPERS.HELP_CONTENT  Single source of truth for every help string the GUI
%   shows in its ⓘ info buttons + Help menu. Keep all human-readable
%   explanations here — `+app/AorticCenterlineApp.m` should never inline
%   help text directly. That way a documentation pass means editing one
%   file, not 9000 lines of UI code.
%
%   entry = ui_helpers.help_content(KEY)  returns a struct with:
%       .title   short header for the modal (1 line)
%       .body    full explanation, can contain newlines / bullets
%       .when    "When to use this" hint (optional)
%       .auto    "What the Automatic mode does instead" (optional)
%
%   Calling with a missing KEY returns an empty-body entry plus a console
%   warning so a typo doesn't crash the GUI.

%   Project: AINN/EVAR (Phase 3)
%   Author : David P. Stonko

    R = registry();
    if isKey(R, key)
        entry = R(key);
    else
        warning('ui_helpers:help_content:missing', ...
            'No help entry for key "%s" — add one in +ui_helpers/help_content.m', key);
        entry = make_entry(key, '', '', '');
    end
end

function R = registry()
%REGISTRY  All help entries. Add new entries here as a single line
%   that calls make_entry(key, title, body, when, auto). Use \n for
%   paragraph breaks.
    R = containers.Map();

    % --- Glossary of clinical terms ---
    R('glossary.all') = make_entry( ...
        'glossary.all', ...
        'Glossary — clinical terms used in this app', ...
        [ ...
        'AAA — Abdominal Aortic Aneurysm. Permanent focal dilation of the abdominal aorta', newline, ...
        '      to >1.5× the normal diameter (clinical threshold for repair typically ≥ 5.5 cm men, ≥ 5.0 cm women).', newline, newline, ...
        'EVAR — Endovascular Aneurysm Repair. Treating an AAA by deploying a covered stent-graft', newline, ...
        '       inside the aneurysm via the femoral arteries, excluding the sac from circulation.', newline, newline, ...
        'TEVAR — Thoracic EVAR. Same idea but for the thoracic / arch aorta.', newline, newline, ...
        'Proximal neck — the segment of normal aorta between the lowest renal artery and the start', newline, ...
        '                of the aneurysm. This is the proximal seal zone for an EVAR device. Its', newline, ...
        '                diameter, length, and angulation determine which devices can be used (IFU).', newline, newline, ...
        'Supraceliac aorta — the aortic segment ABOVE the celiac trunk (T12 vertebral level).', newline, ...
        '                    Used as the proximal anchor for the centerline (5 cm above celiac).', newline, newline, ...
        'Celiac trunk — the first major anterior visceral branch off the abdominal aorta (T12-L1).', newline, ...
        '               Supplies the liver, spleen, and stomach.', newline, newline, ...
        'SMA — Superior Mesenteric Artery. The anterior visceral branch immediately caudal to celiac (L1).', newline, ...
        '      Supplies the small intestine and proximal colon.', newline, newline, ...
        'Renal artery — the bilateral lateral branches at L1-L2 supplying the kidneys. The LOWEST', newline, ...
        '               renal is the distal limit of the proximal seal zone.', newline, newline, ...
        'Aortic bifurcation — where the abdominal aorta divides into the right and left common iliac arteries (L4).', newline, newline, ...
        'CIA — Common Iliac Artery. Runs from the aortic bifurcation to the bifurcation into', newline, ...
        '      internal + external iliac (≈ pelvic brim).', newline, newline, ...
        'EIA — External Iliac Artery. Runs from the CIA bifurcation to the inguinal ligament,', newline, ...
        '      where it becomes the common femoral artery. The EVAR delivery catheter passes', newline, ...
        '      through here.', newline, newline, ...
        'CFA — Common Femoral Artery. The continuation of the EIA below the inguinal ligament.', newline, ...
        '      This is where the EVAR delivery system enters (open or percutaneous access).', newline, newline, ...
        'Internal iliac / hypogastric — branches off the CIA into the pelvis. Coverage during EVAR', newline, ...
        '                              risks buttock claudication / impotence — preserving at least one is preferred.', newline, newline, ...
        'IFU — Instructions For Use. The manufacturer''s document specifying the anatomy a device', newline, ...
        '      is approved for (neck Ø range, neck length min, angulation max, iliac Ø range, etc.).', newline, ...
        '      "On-IFU" = anatomy fits all criteria; "off-IFU" = at least one criterion violated.', newline, newline, ...
        'Type Ia / Ib / II / III endoleak — failure modes of an EVAR. Type Ia = proximal seal failure;', newline, ...
        '       Type Ib = distal seal failure; Type II = back-flow from a side branch; Type III = device', newline, ...
        '       junction or fabric failure. Sizing accuracy is the main lever against Type I leaks.', newline, newline, ...
        'HU (Hounsfield Unit) — CT density scale. Water = 0, air = -1000, cortical bone ≈ 800-1500,', newline, ...
        '      arterial-phase contrast typically 200-500 HU.', newline, newline, ...
        'TotalSegmentator — open-source deep-learning multi-class CT segmenter. Used as the front', newline, ...
        '                  end of this pipeline''s segmentation step.', newline, newline, ...
        'VMTK — Vascular Modeling Toolkit. Open-source library that provides high-quality centerline', newline, ...
        '       extraction via Voronoi diagrams + fast-marching. Used as the preferred centerline backend.' ...
        ], '', '');

    % --- App-level / pipeline overview ---
    R('app.overview') = make_entry( ...
        'app.overview', ...
        'Aortic Centerline Builder — overview', ...
        [ ...
        'This tool turns a contrast-enhanced CT angiogram into a structured EVAR plan.', newline, ...
        'It walks through six steps:', newline, newline, ...
        '  1. Load CT — open a DICOM folder, NIfTI, cached .mat, or a synthetic phantom.', newline, ...
        '  2. Segment — produce a 3-D mask of the aorta + iliacs + common femorals + visceral branches.', newline, ...
        '  3. Pick endpoints — three seeds: proximal aorta (5 cm above celiac), R-CFA, L-CFA.', newline, ...
        '  4. Centerline — bifurcated centerline from each CFA up to the proximal seed.', newline, ...
        '  5. Analyze — measure neck Ø/length/angulation + iliac diameters, match against an IFU library.', newline, ...
        '  6. Export — save the centerline + plan and (optionally) archive the case to the library.', newline, newline, ...
        'Every step has a User-driven / Automatic toggle at the top. User-driven is the default;', newline, ...
        'switch to Automatic when you trust the auto-pipeline on a particular case and just want to', newline, ...
        'sign off on each step''s output.', newline, newline, ...
        'RESEARCH USE ONLY — outputs have not been clinically validated and are not a medical device.' ...
        ], '', '');

    R('app.mode_toggle') = make_entry( ...
        'app.mode_toggle', ...
        'User-driven vs Automatic mode', ...
        [ ...
        'Every step in this app supports two modes:', newline, newline, ...
        '• User-driven (default): you place clicks, tune sliders, and click each button yourself.', newline, ...
        '  Use this when you''re reviewing a difficult case, or when you want to learn how each step works.', newline, newline, ...
        '• Automatic: one button runs the whole step end-to-end with the algorithm''s best defaults.', newline, ...
        '  Use this on routine cases, or to bootstrap a starting point before you refine manually.', newline, newline, ...
        'Both modes produce the same data structure — there is no "easy mode" with lower fidelity.', newline, ...
        'Automatic mode is exactly what `run_planner_headless.m` would do at the command line.', newline, newline, ...
        'The toggle state persists for the current session: re-entering a step keeps your last choice.' ...
        ], '', '');

    R('app.research_only') = make_entry( ...
        'app.research_only', ...
        'Research use only', ...
        [ ...
        'This tool is a research prototype, not an FDA-cleared medical device.', newline, ...
        'Outputs (segmentation, centerlines, sizing, IFU verdicts) have NOT been clinically validated.', newline, ...
        'Do not use any output to plan an actual procedure or guide clinical decision-making.', newline, newline, ...
        'The IFU library values are derived from published peer-reviewed summaries', newline, ...
        '(Chaikof 2018 SVS guidelines, AbuRahma 2018 JACS) and may not match each manufacturer''s', newline, ...
        'official IFU. Always cross-check against the manufacturer''s current IFU document.' ...
        ], '', '');

    % --- Step 1: Load CT ---
    R('step1.overview') = make_entry( ...
        'step1.overview', ...
        'Step 1 — Load CT', ...
        [ ...
        'Load a contrast-enhanced CT angiogram from one of four sources:', newline, newline, ...
        '• DICOM folder — a directory full of .dcm slices from a CT scanner. Single series only;', newline, ...
        '  if the folder contains multiple series the loader picks the largest contiguous volume.', newline, ...
        '• NIfTI file — a .nii or .nii.gz volume (e.g. exported from another tool).', newline, ...
        '• Cached .mat — a previously loaded volume saved by this app.', newline, ...
        '• Phantom — synthetic data shipped with the app for practice / regression testing.', newline, newline, ...
        'After loading, the volume orientation is normalized so z=1 is the most-superior slice', newline, ...
        '(head end), matching standard radiologic display convention.' ...
        ], ...
        'Use a phantom on first use to learn the workflow without needing real DICOM data.', ...
        'In Automatic mode, the app reopens the most-recently-used case.');

    R('step1.recent') = make_entry( ...
        'step1.recent', ...
        'Recent files', ...
        'A rolling list of the last 8 cases you loaded. Click to reopen.', '', '');

    R('step1.phantom') = make_entry( ...
        'step1.phantom', ...
        'Phantom library', ...
        [ ...
        'Synthetic CT volumes shipped with the app:', newline, ...
        '  • PHANTOM_normal_male — straight aorta, normal iliacs', newline, ...
        '  • PHANTOM_aaa_male — 6 cm infrarenal AAA, tortuous left iliac', newline, newline, ...
        'Ground-truth mask, centerline, and seeds are stripped on load so you can work from scratch.', newline, ...
        'Open the original .mat directly to compare against ground truth.'], '', '');

    % --- Step 2: Segment ---
    R('step2.overview') = make_entry( ...
        'step2.overview', ...
        'Step 2 — Segment aorta + iliacs + branches', ...
        [ ...
        'Produce a 3-D binary mask covering: aorta (from above the celiac), celiac trunk, SMA,', newline, ...
        'both renal arteries, common iliacs, external iliacs, and both common femoral arteries.', newline, newline, ...
        'The mask is the substrate for every later step — its quality is the single biggest', newline, ...
        'determinant of downstream accuracy. Spend time here on difficult cases.' ...
        ], ...
        'Aim for a contiguous mask that reaches the inguinal ligament on both sides.', ...
        'Runs TotalSegmentator (deep-learning) + branch extension + CFA walk + supraceliac crop + 6-block audit.');

    R('step2.autoseg') = make_entry( ...
        'step2.autoseg', ...
        'Auto-segment — TotalSegmentator + extensions', ...
        [ ...
        'One-button automated segmentation pipeline:', newline, newline, ...
        '  1. TotalSegmentator (--fast 3-mm model) labels the aorta + both iliacs.', newline, ...
        '  2. extend_and_detect_branches grows iliacs into CFAs, then detects celiac, SMA, and renals.', newline, ...
        '     Includes fallback scans for the SMA and the left renal — these are commonly missed in --fast mode.', newline, ...
        '  3. extend_to_cfa walks each side''s CFA terminus slice-by-slice down to the FOV bottom,', newline, ...
        '     constrained to a side-specific x-band so the extension can never cross the midline.', newline, ...
        '  4. Supraceliac crop — drops the thoracic aorta + arch above 5 cm proximal to the celiac.', newline, ...
        '  5. 6-block audit checks required vessels, visceral branches, anatomic sizes, proximal extent,', newline, ...
        '     per-side continuity, and SE(3) centerline curvature. Reports OK / WARN / FAIL per block.', newline, newline, ...
        'Typical runtime: 1–2 min for TS, then 5–10 seconds for the extensions.' ...
        ], '', '');

    R('step2.ts_targets') = make_entry( ...
        'step2.ts_targets', ...
        'Which structures to segment', ...
        [ ...
        'Check the boxes for the vessels you want TS to label. Defaults match the EVAR workflow:', newline, ...
        '  ✓ aorta', newline, ...
        '  ✓ iliac_artery_left', newline, ...
        '  ✓ iliac_artery_right', newline, ...
        '  ✗ iliac_vena (vein — usually contaminates the arterial mask)', newline, newline, ...
        'Uncheck a structure to skip its TS pass and avoid the time cost.'], '', '');

    R('step2.guided') = make_entry( ...
        'step2.guided', ...
        'Guided 5-click workflow', ...
        [ ...
        'A semi-automated alternative to TotalSegmentator. The app prompts you in order to click:', newline, ...
        '  1. inside the aorta (above the celiac)', newline, ...
        '  2. the lowest renal artery origin', newline, ...
        '  3. the aortic bifurcation', newline, ...
        '  4. inside the R common femoral', newline, ...
        '  5. inside the L common femoral', newline, newline, ...
        'After the 5th click a region-grow runs from each seed in HU 150–500 and the union becomes the mask.', newline, ...
        'Useful when TotalSegmentator is not installed, or as a sanity check.'], '', '');

    R('step2.manual_click') = make_entry( ...
        'step2.manual_click', ...
        'Manual click-to-add vessel mode', ...
        [ ...
        'Switch the toolbar to "2x2 multi-pane", arm pick-vessel mode, then click each vessel', newline, ...
        'on the AXIAL / CORONAL / SAGITTAL panes. Each click runs a HU-bounded region-grow', newline, ...
        'from the clicked voxel. The HU range (default 100–500) is set by the sliders below.', newline, newline, ...
        'Use this when TotalSegmentator drops a vessel entirely (rare for the aorta, more common', newline, ...
        'for small accessory renal arteries or replaced hepatics).'], '', '');

    R('step2.hu_sliders') = make_entry( ...
        'step2.hu_sliders', ...
        'HU range sliders', ...
        [ ...
        'Set the lower and upper Hounsfield Unit bounds for the region-grow.', newline, newline, ...
        'Typical values for arterial-phase CTA:', newline, ...
        '  • Lumen contrast: 200–500 HU (peak ~300–400)', newline, ...
        '  • Calcified plaque: 600+ HU', newline, ...
        '  • Cortical bone: 700–1500 HU', newline, ...
        '  • Soft tissue: 30–80 HU', newline, newline, ...
        'Tighten the upper bound (e.g. to 500) when clicks leak into adjacent bone.', newline, ...
        'Widen the lower bound (e.g. to 150) when the lumen has weak / mixed contrast.'], '', '');

    R('step2.grow_slider') = make_entry( ...
        'step2.grow_slider', ...
        'Grow size slider', ...
        [ ...
        'After every click the region-grow runs unconstrained from the seed.', newline, ...
        'This slider then thresholds the result by geodesic distance — drag LEFT to shrink', newline, ...
        'the visible grow (without re-running anything), drag RIGHT to expand back.', newline, newline, ...
        'Workflow: click a vessel, watch the grow paint the lumen, then drag the slider left if', newline, ...
        'it leaked into neighboring contrast.'], '', '');

    R('step2.brush') = make_entry( ...
        'step2.brush', ...
        'Brush / erase tools', ...
        [ ...
        'Free-form 3-D mask editing.', newline, newline, ...
        '• Click mode — single-voxel toggle.', newline, ...
        '• Brush — drag in any pane to paint mask voxels in a sphere of the chosen radius.', newline, ...
        '• Erase — same shape, but removes voxels.', newline, newline, ...
        'Brush radius is in voxels. At a typical 0.77 mm pixel × 0.5 mm slice spacing,', newline, ...
        '5 voxels ≈ 3 mm — appropriate for small-vessel touch-ups.'], '', '');

    R('step2.display_tools') = make_entry( ...
        'step2.display_tools', ...
        'Display tools — scalpel + bone removal', ...
        [ ...
        'Hide non-vessel anatomy from the 3-D recon (and lock those voxels OUT of the segmentation).', newline, newline, ...
        '• Scalpel — draw a 2-D polygon on the current view; voxels behind the polygon are excluded.', newline, ...
        '• Remove bone — strips voxels with HU > 600 from the display + mask.', newline, ...
        '• Reset display — restores all voxels.', newline, newline, ...
        'Useful when ribs / EKG leads / table / spine clutter the recon and make landmark clicking hard.'], '', '');

    % --- Step 3: Seeds ---
    R('step3.overview') = make_entry( ...
        'step3.overview', ...
        'Step 3 — Pick the three centerline endpoints', ...
        [ ...
        'The bifurcated centerline runs from each common femoral artery up to a single proximal point', newline, ...
        '~5 cm above the celiac. Place three seeds:', newline, newline, ...
        '  ● Proximal aorta (green) — 5 cm above the celiac origin (= ~T12 vertebral level).', newline, ...
        '  ● Right CFA (red) — inside the contrast at the inguinal ligament level on the patient''s right.', newline, ...
        '  ● Left CFA (blue) — same, on the patient''s left.', newline, newline, ...
        'Click each colored button to arm a seed, then click on the mask in any view.', newline, ...
        'Re-arm a seed at any time to refine its position.' ...
        ], ...
        'The proximal seed sets the upper extent of the centerline — don''t put it inside an AAA.', ...
        'Uses the auto_seeds_anatomic module: celiac centroid as the proximal anchor, post-extension CFA termini as the distal seeds.');

    R('step3.audit_summary') = make_entry( ...
        'step3.audit_summary', ...
        'Segmentation audit (from Step 2)', ...
        [ ...
        'The Step 2 audit results are persisted here so you can refer back to them while placing seeds.', newline, newline, ...
        'Six blocks are checked:', newline, ...
        '  1. Required vessels — aorta + bilateral iliacs + bilateral CFAs all present.', newline, ...
        '  2. Visceral branches — celiac + SMA + bilateral renals all detected.', newline, ...
        '  3. Anatomic vessel sizes — supraceliac aorta, mid-iliac, CFA radii within plausible ranges.', newline, ...
        '  4. Proximal extent — mask top is within ±30 mm of 5 cm above celiac.', newline, ...
        '  5. Per-side continuity — each physical side is one connected chain from bifurcation to FOV bottom.', newline, ...
        '  6. SE(3) centerline deformation — Bishop-frame curvature integral within anatomic range.', newline, newline, ...
        'Severity: [OK] passes, [WARN] still allows advance, [FAIL] blocks the audit pass.'], '', '');

    % --- Step 4: Centerline ---
    R('step4.overview') = make_entry( ...
        'step4.overview', ...
        'Step 4 — Compute centerline', ...
        [ ...
        'Compute a 3-D bifurcated centerline: one polyline from R-CFA up to proximal, another from L-CFA', newline, ...
        'up to the same proximal point. The two polylines share a single bifurcation node.', newline, newline, ...
        'Each node carries a radius (inscribed-sphere distance to the mask boundary), so the centerline', newline, ...
        'is also a radius profile — that''s what drives the sizing measurements in Step 5.' ...
        ], '', ...
        'In Automatic mode, the app picks the best available algorithm and computes both centerlines without prompting.');

    R('step4.algorithm') = make_entry( ...
        'step4.algorithm', ...
        'Centerline algorithm — VMTK vs Skeleton', ...
        [ ...
        '• VMTK (vmtkcenterlines) — surface meshing + Voronoi-based fast-marching. Returns a true bifurcating', newline, ...
        '  tree (one source, two targets) with a single shared bifurcation node. Requires VMTK installed', newline, ...
        '  in a conda env. Best quality when it works.', newline, newline, ...
        '• Skeleton (built-in) — bwskel + Dijkstra shortest path on the medial axis, run once per side.', newline, ...
        '  Bifurcation is detected post-hoc by matching the two polylines proximal-to-distal. Pure-MATLAB,', newline, ...
        '  no external deps. Slightly less smooth than VMTK on tortuous anatomy.', newline, newline, ...
        'Defaults to whichever is detected at launch.'], '', '');

    R('step4.guardrail') = make_entry( ...
        'step4.guardrail', ...
        'Arc-length guardrail', ...
        [ ...
        'Sanity check: rejects a centerline whose total arc length is more than N × the straight-line', newline, ...
        'distance between its seed points. Default N = 4.0.', newline, newline, ...
        'When this fires, the Dijkstra path has almost certainly walked up the spine (segmentation leaked', newline, ...
        'into bone). The fix is usually to re-segment with a tighter HU upper bound, not to disable the guard.', newline, newline, ...
        'You can disable the guardrail for cases with genuinely tortuous iliacs where the long path is correct.'], '', '');

    R('step4.editing') = make_entry( ...
        'step4.editing', ...
        'Editing the centerline manually', ...
        [ ...
        'After the initial compute, switch to the 2x2 MPR view. Right-click any centerline node to:', newline, newline, ...
        '  • Insert a new node before / after the clicked node', newline, ...
        '  • Delete the clicked node', newline, ...
        '  • Move the clicked node to a new position (then click again to confirm)', newline, ...
        '  • Recompute the radius at the clicked node from the mask', newline, newline, ...
        'Edits update the radius profile + measurements live.'], '', '');

    % --- Step 5: Analyze ---
    R('step5.overview') = make_entry( ...
        'step5.overview', ...
        'Step 5 — EVAR sizing + IFU match', ...
        [ ...
        'Mark anatomic landmarks on the centerline and let the app derive:', newline, newline, ...
        '  • Proximal neck diameter, length, angulation', newline, ...
        '  • Aortic bifurcation diameter', newline, ...
        '  • Iliac fixation-zone diameters (R + L)', newline, ...
        '  • Distance from lowest renal to aortic bifurcation', newline, ...
        '  • Maximum aneurysm sac diameter (if present)', newline, newline, ...
        'Run the IFU device match button at the bottom to see which devices in the library are eligible.' ...
        ], '', ...
        'Auto mode runs auto-label landmarks (lowest renal + bifurcation from the radius profile) and surfaces measurements + IFU verdict in one click.');

    R('step5.landmarks') = make_entry( ...
        'step5.landmarks', ...
        'Landmark buttons', ...
        [ ...
        'Click a landmark button to arm it, then click on the centerline polyline (red) in any view', newline, ...
        'to place it. Six landmarks supported:', newline, newline, ...
        '  • Lowest renal artery — the most-caudal renal origin (defines the proximal neck distal limit)', newline, ...
        '  • Aortic bifurcation — where the aorta divides into the common iliacs', newline, ...
        '  • R iliac terminus — distal end of the right common iliac', newline, ...
        '  • L iliac terminus — distal end of the left common iliac', newline, ...
        '  • R internal iliac — origin of the right hypogastric (defines distal landing zone)', newline, ...
        '  • L internal iliac — origin of the left hypogastric'], '', '');

    R('step5.auto_label') = make_entry( ...
        'step5.auto_label', ...
        'Auto-label landmarks', ...
        [ ...
        'Heuristic auto-labels two clinically critical landmarks:', newline, newline, ...
        '  • Aortic bifurcation — already known from the centerline''s bifurcation node.', newline, ...
        '  • Lowest renal — the radius minimum in the aortic portion of the right polyline (proximal neck).', newline, newline, ...
        'You can refine either by clicking its landmark button and placing it manually.'], '', '');

    R('step5.ifu_match') = make_entry( ...
        'step5.ifu_match', ...
        'IFU device match', ...
        [ ...
        'Runs the case through every device in the IFU library and reports per-device eligibility +', newline, ...
        'binding constraint. The 5 devices currently in the library are:', newline, newline, ...
        '  • Gore Excluder', newline, ...
        '  • Medtronic Endurant II', newline, ...
        '  • Cook Zenith Flex', newline, ...
        '  • Endologix AFX2', newline, ...
        '  • Terumo Treo', newline, newline, ...
        'IFU thresholds are derived from published peer-reviewed summaries — see the Research-only', newline, ...
        'help entry for the citations. Always cross-check against the manufacturer''s current IFU.'], '', '');

    % --- Reference annotations + benchmark runner ---
    R('reference.overview') = make_entry( ...
        'reference.overview', ...
        'Reference annotations (TeraRecon comparison)', ...
        [ ...
        'A reference annotation is a JSON file capturing the gold-standard EVAR measurements an expert', newline, ...
        'made on a case (typically in TeraRecon Aquarius / iNtuition). The +reference package owns the', newline, ...
        'schema; `scripts/run_benchmark.m` pairs each CT case with its reference JSON, runs the', newline, ...
        'automated planner, and emits a per-case delta CSV.', newline, newline, ...
        'Workflow to add a new case to the benchmark corpus:', newline, ...
        '  1. reference.template(''CASE_NAME'', ref_dir)  →  writes CASE_NAME.ref.json with NaN fields', newline, ...
        '  2. Open the JSON, fill in the measurements you made in TeraRecon, save', newline, ...
        '  3. Put the CT for CASE_NAME under cohort_root/CASE_NAME/', newline, ...
        '  4. results = run_benchmark(cohort_root, ref_dir)', newline, newline, ...
        'Measurement fields recorded (mm + degrees):', newline, ...
        '  neck_diameter_mm, neck_length_mm, neck_angulation_deg', newline, ...
        '  iliac_R_diameter_mm, iliac_R_length_mm, iliac_L_diameter_mm, iliac_L_length_mm', newline, ...
        '  aneurysm_max_diameter_mm', newline, ...
        '  distance_lowest_renal_to_bifurcation_mm', newline, ...
        '  bifurcation_angle_deg', newline, newline, ...
        'See docs/TERARECON_ANNOTATION_GUIDE.md for a field-by-field guide to where each', newline, ...
        'value lives in TeraRecon. Any field can be NaN if the anatomy isn''t present or', newline, ...
        'wasn''t measured confidently.' ...
        ], ...
        'Use this when you''re ready to capture ground-truth measurements for a TeraRecon-vs-planner comparison.', ...
        'No automatic substitute — measurement annotation IS the manual step.');

    % --- Step 6: Export ---
    R('step6.overview') = make_entry( ...
        'step6.overview', ...
        'Step 6 — Export', ...
        [ ...
        'Save the results of this session. Three output paths:', newline, newline, ...
        '  • Save centerline.mat — the bifurcated centerline + radii + seeds (engineering format).', newline, ...
        '  • Save EVAR plan — a structured .txt + .json with the measurements, IFU match, and rationale.', newline, ...
        '  • Add to library — archive the entire case (CT + mask + centerline + landmarks + plan) for later reuse.' ...
        ], '', ...
        'Auto mode writes all three to the default output directory and prints a summary.');

    R('step6.library') = make_entry( ...
        'step6.library', ...
        'Case library', ...
        [ ...
        'A directory of completed cases used as a benchmark corpus. Each case is a .mat with the full', newline, ...
        'planner state — re-open one to compare against the current case or to bootstrap a similar one.', newline, newline, ...
        'Library cases are also the inputs for the regression test suite, so adding a case can act as', newline, ...
        'an integration test for future code changes.'], '', '');
end

function e = make_entry(key, title, body, when, auto)
%MAKE_ENTRY  Build a help-entry struct with sensible defaults.
    if nargin < 4; when = ''; end
    if nargin < 5; auto = ''; end
    e = struct('key', key, 'title', title, 'body', body, 'when', when, 'auto', auto);
end
