function install_help(parent_fig)
%SETUP.INSTALL_HELP  Open a uifigure with copy-pasteable install
%   commands for the optional Python tools the EVAR planner can use.
%
%   setup.install_help()
%   setup.install_help(PARENT_FIG)
%
%   The dialog is non-modal; the user can leave it open while they
%   run the install in a terminal and then re-check status from the
%   main GUI.

%   Project: AINN/EVAR (Phase 3)
%   Author : David P. Stonko

    arguments
        parent_fig = []
    end

    f = uifigure('Name', 'Install help — external tools', ...
        'Position', [200 200 720 560], 'Color', 'w');
    if ~isempty(parent_fig) && isvalid(parent_fig)
        % Center over the parent
        pp = parent_fig.Position;
        f.Position(1) = pp(1) + (pp(3) - f.Position(3))/2;
        f.Position(2) = pp(2) + (pp(4) - f.Position(4))/2;
    end

    uilabel(f, 'Position', [20 510 680 30], ...
        'Text', 'External tools — installation', ...
        'FontSize', 16, 'FontWeight', 'bold');
    uilabel(f, 'Position', [20 470 680 36], ...
        'Text', ['Both tools are optional. The EVAR planner runs the ' ...
                 'manual click-to-add and skeleton-centerline paths ' ...
                 'with no Python dependency. Installing these unlocks ' ...
                 'auto-segmentation and the bifurcating-tree centerline.'], ...
        'WordWrap', 'on', 'FontSize', 12, 'FontColor', [0.3 0.3 0.3]);

    % --- TotalSegmentator ----------------------------------------
    uilabel(f, 'Position', [20 430 680 22], ...
        'Text', 'TotalSegmentator (auto-segmentation)', ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'FontColor', [0.10 0.45 0.20]);
    uilabel(f, 'Position', [20 400 680 28], ...
        'Text', ['Wasserthal et al., Radiology AI 2023. Apache 2.0. ' ...
                 'github.com/wasserth/TotalSegmentator'], ...
        'WordWrap', 'on', 'FontSize', 11, 'FontColor', [0.4 0.4 0.4]);
    cmd_ts = sprintf(['conda create -n evar-tools python=3.11 -y\n' ...
                      'conda activate evar-tools\n' ...
                      'pip install TotalSegmentator']);
    uitextarea(f, 'Position', [20 320 680 80], ...
        'Value', cmd_ts, 'Editable', 'off', ...
        'FontName', 'Menlo', 'FontSize', 12);

    % --- VMTK -----------------------------------------------------
    uilabel(f, 'Position', [20 280 680 22], ...
        'Text', 'VMTK (Voronoi-based centerlines)', ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'FontColor', [0.10 0.20 0.55]);
    uilabel(f, 'Position', [20 250 680 28], ...
        'Text', ['Antiga et al., Med Biol Eng Comput 2008. BSD-3. ' ...
                 'vmtk.org'], ...
        'WordWrap', 'on', 'FontSize', 11, 'FontColor', [0.4 0.4 0.4]);
    cmd_vmtk = sprintf(['conda create -n vmtk -c vmtk -c conda-forge ' ...
                        'vmtk python=3.10 -y\n' ...
                        'conda activate vmtk']);
    uitextarea(f, 'Position', [20 170 680 80], ...
        'Value', cmd_vmtk, 'Editable', 'off', ...
        'FontName', 'Menlo', 'FontSize', 12);

    uilabel(f, 'Position', [20 130 680 32], ...
        'Text', ['After installation, both CLIs need to be on PATH ' ...
                 'when MATLAB launches. On macOS/Linux, activate the ' ...
                 'env in the shell that starts MATLAB.'], ...
        'WordWrap', 'on', 'FontSize', 11, 'FontColor', [0.3 0.3 0.3]);

    uibutton(f, 'push', ...
        'Position', [20 70 200 36], ...
        'Text', 'Re-check status', 'FontSize', 12, ...
        'BackgroundColor', [0.85 0.95 0.85], ...
        'ButtonPushedFcn', @(~,~) recheck(parent_fig));
    uibutton(f, 'push', ...
        'Position', [240 70 100 36], ...
        'Text', 'Close', 'FontSize', 12, ...
        'ButtonPushedFcn', @(~,~) delete(f));
end

% =========================================================================
function recheck(parent_fig)
    s = setup.check_dependencies();
    msg = sprintf('TotalSegmentator: %s\nVMTK: %s', ...
        avail_str(s.totalsegmentator), avail_str(s.vmtk));
    if isempty(parent_fig) || ~isvalid(parent_fig)
        uiwait(msgbox(msg, 'Status', 'modal'));
    else
        uialert(parent_fig, msg, 'Dependency status', 'Icon', 'info');
    end
end

function s = avail_str(d)
    if d.available; s = 'available ✓'; else; s = 'not found ✗'; end
end
