function out_path = write_slicer_color_table(out_path, class_map_path)
%INTAKE.WRITE_SLICER_COLOR_TABLE  Generate a 3D Slicer color table (.ctbl)
%   for the Set-A annotation scheme, so every segment carries the correct
%   paint-ID and name automatically instead of being assigned by hand.
%
%   PATH = intake.write_slicer_color_table()
%   PATH = intake.write_slicer_color_table(OUT_PATH)
%   PATH = intake.write_slicer_color_table(OUT_PATH, CLASS_MAP_PATH)
%
%   Reads the Set-A class map (default data/setA_class_map.json) and writes
%   a Slicer color-table file keyed by the SOP paint-IDs (the ids the
%   annotator paints in), one colour per structure. Load it in Slicer via
%   the Colors module (Add → from file) or set it as the colour node on the
%   Segmentation, then paint — segment 8 is "left_common_iliac", etc.
%
%   Format is Slicer's plain color table: `id name R G B A` (0-255),
%   comment lines start with '#'. Regenerate whenever the class map changes
%   so the two never drift.

%   Project: AINN/EVAR (Phase 3)
%   Author : David P. Stonko

    arguments
        out_path       (1,:) char = ''
        class_map_path (1,:) char = ''
    end
    here = fileparts(mfilename('fullpath'));           % +intake/
    proj = fileparts(here);                            % project root
    if isempty(class_map_path)
        class_map_path = fullfile(proj, 'data', 'setA_class_map.json');
    end
    if isempty(out_path)
        out_path = fullfile(proj, 'data', 'setA_slicer_colors.ctbl');
    end
    if ~exist(class_map_path, 'file')
        error('intake:write_slicer_color_table:NoClassMap', ...
            'Class map not found: %s', class_map_path);
    end

    txt = fileread(class_map_path);
    cm  = jsondecode(txt);
    cl  = cm.classes;
    if iscell(cl); cl = [cl{:}]; end

    % Distinct colour per structure, grouped by territory (paint-id → RGB).
    colours = containers.Map('KeyType', 'double', 'ValueType', 'any');
    colours(1)  = [220  40  40];   % aorta        — red
    colours(4)  = [230 140  30];   % celiac       — orange
    colours(5)  = [240 185  40];   % SMA          — amber
    colours(6)  = [150  80 200];   % L renal      — purple
    colours(7)  = [185 110 220];   % R renal      — violet
    colours(8)  = [ 40  90 205];   % L com iliac  — blue
    colours(9)  = [ 60 120 225];   % R com iliac  — blue
    colours(10) = [ 35 160 175];   % L ext iliac  — teal
    colours(11) = [ 55 180 195];   % R ext iliac  — teal
    colours(12) = [120 120 120];   % L int iliac  — grey
    colours(13) = [150 150 150];   % R int iliac  — grey
    colours(24) = [ 40 170  70];   % L CFA        — green
    colours(25) = [ 70 195  95];   % R CFA        — green

    max_id = 0;
    for k = 1:numel(cl); max_id = max(max_id, double(cl(k).id)); end

    fid = fopen(out_path, 'w');
    if fid < 0
        error('intake:write_slicer_color_table:OpenFailed', ...
            'Could not open %s for writing.', out_path);
    end
    cleaner = onCleanup(@() fclose(fid));

    fprintf(fid, '# 3D Slicer color table — EVAR Set-A annotation scheme\n');
    fprintf(fid, '# Generated by intake.write_slicer_color_table from %s\n', ...
        class_map_path);
    fprintf(fid, '# Columns: id name R G B A  (0-255). Paint IDs match the SOP.\n');
    fprintf(fid, '0 background 0 0 0 0\n');
    for id = 1:max_id
        idx = find([cl.id] == id, 1);
        if isempty(idx); continue; end               % gaps stay unlisted
        name = cl(idx).name;
        if isKey(colours, id)
            c = colours(id);
        else
            c = [200 200 200];                        % fallback grey
        end
        fprintf(fid, '%d %s %d %d %d 255\n', id, name, c(1), c(2), c(3));
    end
end
