function db = devices()
%IFU.DEVICES  Structured library of EVAR stent-graft IFU criteria.
%
%   DB = ifu.devices() returns a struct array with one entry per
%   stent-graft system, encoding the anatomic indications from the
%   manufacturer's US labeling.
%
%   IMPORTANT — research use only. Values were checked on 2026-09-29
%   against the manufacturer / FDA documents cited in each entry's
%   `.source` (document numbers included). Labeling changes over time;
%   `.last_verified` records when each entry was checked. DO NOT use this
%   library for clinical decision-making without the current vendor IFU.
%
%   Each entry has fields:
%       .name                   short name (e.g. 'Excluder')
%       .manufacturer           manufacturer
%       .body_design            'bifurcated' | 'unibody' | 'tubular'
%       .neck_diameter_mm       [min max] proximal neck diameter
%       .neck_length_min_mm     minimum non-aneurysmal infrarenal neck length
%       .neck_angulation_max_deg max INFRARENAL neck angulation (checked
%                               against beta, measure_from_centerline's
%                               neck_angulation_deg)
%       .suprarenal_angulation_max_deg  max SUPRARENAL angle (checked
%                               against alpha); NaN when not labeled
%       .short_neck_angle_rule  [L_mm angle_deg] — if the neck is shorter
%                               than L_mm the infrarenal limit tightens to
%                               angle_deg (Ovation); [] when none
%       .iliac_diameter_mm      [min max] iliac landing zone diameter
%       .iliac_length_min_mm    minimum iliac seal length
%       .iliac_bifurc_angle_max_deg  max iliac angle to the bifurcation;
%                               NaN when not labeled
%       .access_min_mm          minimum access vessel diameter (not yet
%                               measured by the planner); NaN if unlabeled
%       .diameter_basis         'outer' | 'inner' | 'unspecified' — how the
%                               IFU defines its diameters. The planner
%                               measures LUMEN diameters, which under-call
%                               an outer-wall definition wherever there is
%                               wall/thrombus (see check_eligibility).
%       .source                 citation (manufacturer / FDA document)
%       .last_verified          ISO date the source was checked
%       .notes                  free-text caveats

%   Project: AINN/EVAR (Phase 3)
%   Author : David P. Stonko

    db = struct( ...
        'name', {}, 'manufacturer', {}, 'body_design', {}, ...
        'neck_diameter_mm', {}, 'neck_length_min_mm', {}, ...
        'neck_angulation_max_deg', {}, 'suprarenal_angulation_max_deg', {}, ...
        'short_neck_angle_rule', {}, ...
        'iliac_diameter_mm', {}, 'iliac_length_min_mm', {}, ...
        'iliac_bifurc_angle_max_deg', {}, 'access_min_mm', {}, ...
        'diameter_basis', {}, ...
        'source', {}, 'last_verified', {}, 'notes', {});

    db(end+1) = entry('Excluder', 'W.L. Gore', 'bifurcated', ...
        [19 32], 15, 60, [8 25], 10, ...
        'W.L. Gore, GORE EXCLUDER AAA Endoprosthesis specifications, doc. 24AR1142-EN02 (goremedical.com)', ...
        '2026-09-29', ...
        'IFU states "treatment diameter" without specifying inner vs outer wall.');
    db(end).diameter_basis = 'unspecified';

    db(end+1) = entry('Endurant II', 'Medtronic', 'bifurcated', ...
        [19 32], 10, 60, [8 25], 15, ...
        ['Chaikof EL, et al. J Vasc Surg 2018;67(1):2-77.e2; consistent with the ' ...
         'Medtronic Endurant II/IIs US sizing sheet UC202301796aEN (2026-09-29 audit, secondary check)'], ...
        '2026-05-16', ...
        ['US labeling: ≥10 mm neck (≥4 mm with EndoAnchors), where neck length is the ' ...
         'length within 10% of the infrarenal diameter; OUS labeling allows ≤75° with a ≥15 mm neck.']);
    db(end).diameter_basis = 'unspecified';

    db(end+1) = entry('Zenith Flex', 'Cook Medical', 'bifurcated', ...
        [18 32], 15, 60, [7.5 20], 10, ...
        'Cook Medical, Zenith Flex AAA Endovascular Graft indications for use (pocket guide AI-D22611-EN-F)', ...
        '2026-09-29', ...
        ['Diameters are OUTER wall to outer wall. IFU uses strict limits (infrarenal <60°, ' ...
         'suprarenal <45°, iliac length >10 mm); boundary values are treated as eligible here.']);
    db(end).suprarenal_angulation_max_deg = 45;
    db(end).diameter_basis = 'outer';

    db(end+1) = entry('AFX2', 'Endologix', 'unibody', ...
        [18 32], 15, 60, [10 23], 15, ...
        'Endologix, AFX2 Endovascular AAA System indications for use (US), MM1111-ALL Rev 04, 2024', ...
        '2026-09-29', ...
        ['Unibody design seats on the aortic bifurcation. Also requires aortic length ≥1.0 cm ' ...
         'longer than the chosen body and preservation of ≥1 hypogastric (not checked).']);
    db(end).iliac_bifurc_angle_max_deg = 90;
    db(end).access_min_mm = 6.5;
    db(end).diameter_basis = 'unspecified';

    db(end+1) = entry('Treo', 'Terumo Aortic', 'bifurcated', ...
        [17 32], 15, 60, [8 20], 10, ...
        'Terumo Aortic, TREO Abdominal Stent-Graft System IFU, FDA PMA P190015 (approved 2020)', ...
        '2026-09-29', ...
        ['Iliac seal is tiered on INSIDE diameter: 8-13 mm needs ≥10 mm, >13-20 mm needs ' ...
         '≥15 mm. Also needs ≥13 cm treatment length and ≥9 cm lowest-renal-to-bifurcation (not checked).']);
    db(end).suprarenal_angulation_max_deg = 45;
    db(end).diameter_basis = 'inner';

    db(end+1) = entry('Ovation iX', 'Endologix (TriVascular)', 'bifurcated', ...
        [16 30], 7, 60, [8 20], 10, ...
        'TriVascular, Ovation Abdominal Stent Graft System IFU, FDA PMA P120006 (810-0010-01-01 Rev A)', ...
        '2026-09-29', ...
        ['Polymer-filled sealing rings; neck and iliac limits are INNER wall. Criteria are from the ' ...
         'original Ovation IFU; Ovation iX shares the platform and has been succeeded by ALTO.']);
    db(end).short_neck_angle_rule = [10 45];
    db(end).diameter_basis = 'inner';

    db(end+1) = entry('Excluder Conformable', 'W.L. Gore', 'bifurcated', ...
        [16 32], 10, 90, [8 25], 10, ...
        'W.L. Gore, GORE EXCLUDER Conformable AAA Endoprosthesis specifications, doc. 25AR6045-EN01 (goremedical.com)', ...
        '2026-09-29', ...
        'Active angulation control; labeled to ≤90° neck angulation with a ≥10 mm neck.');
    db(end).diameter_basis = 'unspecified';
end

function s = entry(name, mfg, design, neck_dia, neck_len, neck_ang, ...
                   ili_dia, ili_len, src, ver, notes)
    % Optional constraints default to "not labeled" (NaN / []) and are
    % set per device after construction; check_eligibility skips a NaN
    % constraint rather than inventing one.
    s = struct( ...
        'name', name, 'manufacturer', mfg, 'body_design', design, ...
        'neck_diameter_mm', neck_dia, 'neck_length_min_mm', neck_len, ...
        'neck_angulation_max_deg', neck_ang, ...
        'suprarenal_angulation_max_deg', NaN, ...
        'short_neck_angle_rule', [], ...
        'iliac_diameter_mm', ili_dia, 'iliac_length_min_mm', ili_len, ...
        'iliac_bifurc_angle_max_deg', NaN, 'access_min_mm', NaN, ...
        'diameter_basis', 'unspecified', ...
        'source', src, 'last_verified', ver, 'notes', notes);
end
