function db = devices()
%IFU.DEVICES  Structured library of EVAR stent-graft IFU criteria.
%
%   DB = ifu.devices() returns a struct array with one entry per
%   stent-graft system. Fields describe the labeled-use anatomic
%   criteria as reported in peer-reviewed summaries.
%
%   IMPORTANT — research use only. The numbers below are taken from
%   PEER-REVIEWED PUBLISHED SUMMARIES (Chaikof 2018 SVS guidelines and
%   AbuRahma 2018 JACS, see references at the end of this file) and
%   are NOT a substitute for the manufacturer's current Instructions
%   for Use. Vendor IFUs are updated periodically and may differ from
%   the values encoded here. Every device entry carries a `.source`
%   citation and a `.last_verified` date. DO NOT use this library for
%   clinical decision-making without checking the current vendor IFU.
%
%   Each entry has fields:
%       .name                   short name (e.g. 'Excluder')
%       .manufacturer           manufacturer
%       .body_design            'bifurcated' | 'unibody' | 'tubular'
%       .neck_diameter_mm       [min max] proximal neck diameter
%       .neck_length_min_mm     minimum non-aneurysmal infrarenal neck length
%       .neck_angulation_max_deg max infrarenal neck angulation. Checked
%                               against the infrarenal neck-to-sac angle
%                               (beta) that measure_from_centerline emits
%                               as neck_angulation_deg — the angle most
%                               vendor IFUs limit on.
%       .iliac_diameter_mm      [min max] iliac landing zone diameter
%       .iliac_length_min_mm    minimum iliac landing zone length
%       .iliac_bifurc_angle_max_deg  max iliac take-off (bifurcation)
%                               angle per vendor IFU. NaN when not
%                               published. Added 2026-05-21.
%       .source                 citation
%       .last_verified          ISO date the source was checked
%       .notes                  free-text caveats

%   Project: AINN/EVAR (Phase 3)
%   Author : David P. Stonko

    src_chaikof_2018 = ['Chaikof EL, et al. The SVS practice guidelines on the care of ' ...
                        'patients with an abdominal aortic aneurysm. J Vasc Surg 2018;67(1):2-77.e2.'];
    src_aburahma_2018 = ['AbuRahma AF, et al. Aortic neck anatomic features and predictors ' ...
                         'of outcomes in EVAR following vs not following IFU. ' ...
                         'J Am Coll Surg 2018;227(3):350-359.'];

    db = struct( ...
        'name', {}, 'manufacturer', {}, 'body_design', {}, ...
        'neck_diameter_mm', {}, 'neck_length_min_mm', {}, ...
        'neck_angulation_max_deg', {}, ...
        'iliac_diameter_mm', {}, 'iliac_length_min_mm', {}, ...
        'iliac_bifurc_angle_max_deg', {}, ...
        'source', {}, 'last_verified', {}, 'notes', {});

    db(end+1) = entry('Excluder', 'W.L. Gore', 'bifurcated', ...
        [19 29], 15, 60, [8 18.5], 10, ...
        src_chaikof_2018, '2026-05-16', ...
        'Standard Excluder; conformable variant (Excluder C3 / Conformable) has wider angulation tolerance (≤ 90°) per vendor labeling.');

    db(end+1) = entry('Endurant II', 'Medtronic', 'bifurcated', ...
        [19 32], 10, 60, [8 25], 15, ...
        src_chaikof_2018, '2026-05-16', ...
        'Some sources tabulate neck angulation up to 75°; the more conservative 60° threshold is used here and matches Chaikof 2018 Table.');

    db(end+1) = entry('Zenith Flex', 'Cook Medical', 'bifurcated', ...
        [18 32], 15, 60, [7.5 20], 10, ...
        src_chaikof_2018, '2026-05-16', ...
        'Suprarenal fixation; barbs require ≥ 4 mm of suprarenal aorta.');

    db(end+1) = entry('AFX2', 'Endologix', 'unibody', ...
        [18 29], 15, 60, [10 23], 15, ...
        src_aburahma_2018, '2026-05-16', ...
        'Unibody design seats at the bifurcation; iliac diameter range reflects standard AFX2 (not Endologix Ovation).');

    db(end+1) = entry('Treo', 'Terumo Aortic', 'bifurcated', ...
        [17 32], 10, 60, [7 25], 15, ...
        src_aburahma_2018, '2026-05-16', ...
        'Formerly Bolton Medical Treovance; CE-marked, FDA approval 2017.');

    db(end+1) = entry('Ovation iX', 'Endologix (Trivascular)', 'bifurcated', ...
        [16 30], 7, 60, [8 25], 10, ...
        src_aburahma_2018, '2026-05-17', ...
        ['Polymer-filled sealing rings instead of a self-expanding stent in the neck. ' ...
         'Tolerates short necks (≥ 7 mm) better than self-expanding devices; ' ...
         'small 14 Fr delivery (lower bound iliac is permissive). ' ...
         'No iliac max in source — using common-range ceiling of 25 mm.']);

    db(end+1) = entry('Excluder Conformable (C3)', 'W.L. Gore', 'bifurcated', ...
        [19 29], 15, 90, [8 25], 10, ...
        src_chaikof_2018, '2026-05-17', ...
        ['Conformable variant of the Gore Excluder; widened angulation tolerance ' ...
         'to ≤ 90° per vendor labeling. Same neck-diameter window as the standard ' ...
         'Excluder. Use when standard Excluder fails on angulation only.']);
end

function s = entry(name, mfg, design, neck_dia, neck_len, neck_ang, ...
                   ili_dia, ili_len, src, ver, notes)
    % `iliac_bifurc_angle_max_deg` (added 2026-05-21) is an optional
    % constraint slot for vendor-specified maximum iliac take-off
    % (bifurcation) angle. Default NaN means "no published constraint
    % in this device's IFU summary" → check_eligibility skips the
    % check. Populate from real vendor IFUs as that data is gathered.
    s = struct( ...
        'name', name, 'manufacturer', mfg, 'body_design', design, ...
        'neck_diameter_mm', neck_dia, 'neck_length_min_mm', neck_len, ...
        'neck_angulation_max_deg', neck_ang, ...
        'iliac_diameter_mm', ili_dia, 'iliac_length_min_mm', ili_len, ...
        'iliac_bifurc_angle_max_deg', NaN, ...
        'source', src, 'last_verified', ver, 'notes', notes);
end
